name: Deploy others folder to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'others/**'
      - '.github/workflows/deploy-others.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: others # The folder the action should deploy.
          target-folder: others # The destination folder on the gh-pages branch.
          clean: false # Do not clean the branch before deploying.
